#' Generate Niche Similarity Map
#'
#' This function generates a continuous niche similarity map (dot product) in Google Earth Engine
#' based on the species centroid. The map is returned at the specified resolution.
#'
#' @param df Data frame containing the original survey data (Latitude, Longitude) to determine the AOI.
#' @param analysis_meta_path Path to the JSON metadata file generated by `analyze_embeddings`.
#' @param output_dir Directory where the output map and metadata will be saved. Defaults to current working directory.
#' @param scale Resolution in meters for the output map. Defaults to 10.
#' @param coarse_meta_path Optional. Path to metadata for 1km filtering. If provided, analysis is restricted to 1km pixels > 5th percentile.
#' @param gcs_bucket Optional. GCS bucket name for server-side export. If provided, bypasses local download.
#' @param wait Logical. If TRUE, waits for the GCS export task(s) to complete and shows progress updates.
#' @param zip Logical. If TRUE, zips the output rasters into a single archive (local mode only).
#' @return A list containing the paths to the generated map files, HTML, or GCS export details.
#' @keywords internal
extrapolate <- function(df, analysis_meta_path, output_dir = getwd(), scale = NULL, aoi_year = NULL, view = FALSE, gcs_bucket = NULL, wait = FALSE, zip = FALSE, python_path = NULL, gee_project = NULL) {
  if (!is.null(gee_project)) gee_project <- as.character(gee_project)
  # 1. GEE Auth
  ensure_gee_authenticated(project = gee_project)
  ee <- reticulate::import("ee")

  if (is.null(scale)) stop("Parameter 'scale' (resolution in meters) must be provided.")
  if (is.null(aoi_year)) stop("Parameter 'aoi_year' must be provided.")

  # 2. Load Model Metadata
  if (!file.exists(analysis_meta_path)) stop("Metadata file not found: ", analysis_meta_path)
  meta <- jsonlite::fromJSON(analysis_meta_path)

  # 3. Prepare GEE Geometry from df
  bbox <- c(min(df$longitude), min(df$latitude), max(df$longitude), max(df$latitude))
  aoi_geom <- ee$Geometry$Rectangle(bbox)$buffer(1000) # 1km buffer

  # 4. Generate Prediction Map
  img_mosaic <- get_embedding_image(aoi_year, scale)
  
  prediction <- NULL
  if (!meta$is_classifier) {
    # Reducer dot product
    weights_ee <- ee$Image$constant(as.list(meta$weights))$rename(sprintf("A%02d", 0:63))
    prediction <- img_mosaic$multiply(weights_ee)$reduce(ee$Reducer$sum())$add(meta$intercept)$rename("similarity")
  } else {
    # Classifier prediction
    # NOTE: In a pure R implementation, we might need to re-train the GEE classifier
    # if we don't have a serialized version. For now, we'll mark this as limited.
    stop("Classifier extrapolation in pure R currently requires re-training or a serialized GEE model ID.")
  }

  # 5. Output
  m_clean <- gsub("[^a-zA-Z0-9]", "", meta$method)
  tif_path <- file.path(output_dir, paste0(m_clean, "_extrapolation.tif"))
  
  message("Exporting extrapolation map to ", tif_path, "...")
  try(rgee::ee_as_rast(image = prediction, region = aoi_geom, scale = scale, dsn = tif_path), silent = TRUE)

  return(list(map_path = tif_path, method = meta$method))
}

#' Predict at Specific Coordinates
#'
#' @param df Data frame with columns `longitude`, `latitude`, and `year`.
#' @param analysis_meta_paths Vector of paths to metadata JSON files.
#' @param scale Resolution in meters.
#' @param aoi_year Year for Alpha Earth mosaic.
#' @param gee_project GEE Project ID.
#' @param options Named list of advanced hyperparameters.
#' @return A list with data (df + similarity) and metrics.
#' @export
predict_at_coords <- function(df, analysis_meta_paths, scale = NULL, aoi_year = NULL, gee_project = NULL, options = list()) {
  if (!is.null(gee_project)) gee_project <- as.character(gee_project)
  # 1. GEE Auth
  ensure_gee_authenticated(project = gee_project)
  
  if (is.null(scale)) stop("Parameter 'scale' must be provided.")
  if (is.null(aoi_year)) stop("Parameter 'aoi_year' must be provided.")
  
  # 2. Upload and Score on GEE
  message("Predicting at coordinates (Server-side)...")
  
  # 1. Upload points and sample embeddings (stays on GEE)
  upload_fc <- upload_points_to_gee(df)
  sampled_fc <- get_embeddings_at_fc(upload_fc, scale, properties = c("year", "tmp_id"))
  
    # results data
    final_results <- df
    scored_fc <- sampled_fc
    
    # 3. Score for each model
    message(sprintf("  Scoring %d model(s)...", length(analysis_meta_paths)))
    models_to_score <- list()
    for (mp in analysis_meta_paths) {
        if (!file.exists(mp)) next
        meta <- jsonlite::fromJSON(mp)
        m <- meta$method
        model_res <- list(
            method = m,
            is_classifier = meta$is_classifier,
            trained = NULL 
        )
        if (!meta$is_classifier) {
            model_res$weights <- as.numeric(meta$weights)
            model_res$intercept <- as.numeric(meta$intercept)
        }
        models_to_score[[m]] <- model_res
    }
    
    # Run the optimized prediction pipeline
    scored_fc <- predict_all_models_gee(sampled_fc, models_to_score)
    
    # 4. Download results (Parallel Batched CSV)
    selectors <- as.list(c("tmp_id", paste0("pred_", names(models_to_score))))
    safe_chunk_size <- if (scale <= 160) 5000 else 10000
    chunk_size <- max(safe_chunk_size, ceiling(nrow(df) / 40))
    batch_starts <- seq(1, nrow(df), by = chunk_size)
    n_cores <- min(length(batch_starts), parallel::detectCores(logical = FALSE), 40L)
    
    message(sprintf("  Downloading results across %d parallel batches...", length(batch_starts)))
    
    process_batch <- function(idx) {
        # Re-import ee inside parallel worker to avoid closure/fork issues
        ee <- reticulate::import("ee")
        i <- batch_starts[idx]
        end_idx <- min(i + chunk_size - 1, nrow(df))
        chunk_fc <- scored_fc$filter(ee$Filter$gte("tmp_id", as.integer(i-1)))$
                             filter(ee$Filter$lte("tmp_id", as.integer(end_idx-1)))
                             
        for (attempt in seq_len(5L)) {
            res <- tryCatch({
                url <- chunk_fc$getDownloadURL(filetype = "CSV", selectors = selectors)
                read.csv(url)
            }, error = function(e) e)
            if (is.data.frame(res)) return(res)
            Sys.sleep(2^(attempt - 1) + runif(1, 0, 1))
        }
        data.frame()
    }
    
    all_res_list <- if (.Platform$OS.type == "unix") {
        parallel::mclapply(seq_along(batch_starts), process_batch, mc.cores = n_cores)
    } else {
        lapply(seq_along(batch_starts), process_batch)
    }
    
    res_df <- do.call(rbind, all_res_list)
    
    # Re-attach scores
    if (!is.null(res_df) && nrow(res_df) > 0) {
        res_df <- res_df[order(res_df$tmp_id), ]
        idx <- match(res_df$tmp_id, (seq_len(nrow(df)) - 1))
        valid_mask <- !is.na(idx)
        for (m in names(models_to_score)) {
            col_name <- if (length(analysis_meta_paths) > 1) paste0("similarity_", m) else "similarity"
            final_results[idx[valid_mask], col_name] <- as.numeric(res_df[[paste0("pred_", m)]][valid_mask])
        }
    }
    
    return(list(data = final_results, metrics = list()))
}
