#' Generate Niche Similarity Map
#'
#' This function generates a continuous niche similarity map (dot product) in Google Earth Engine
#' based on the species centroid. The map is returned at the specified resolution.
#'
#' @param df Data frame containing the original survey data (Latitude, Longitude) to determine the AOI.
#' @param analysis_meta_path Path to the JSON metadata file generated by `analyze_embeddings`.
#' @param output_dir Directory where the output map and metadata will be saved. Defaults to current working directory.
#' @param scale Resolution in meters for the output map. Defaults to 10.
#' @param coarse_meta_path Optional. Path to metadata for 1km filtering. If provided, analysis is restricted to 1km pixels > 5th percentile.
#' @param gcs_bucket Optional. GCS bucket name for server-side export. If provided, bypasses local download.
#' @param wait Logical. If TRUE, waits for the GCS export task(s) to complete and shows progress updates.
#' @param zip Logical. If TRUE, zips the output rasters into a single archive (local mode only).
#' @return A list containing the paths to the generated map files, HTML, or GCS export details.
#' @keywords internal
extrapolate <- function(df, analysis_meta_path, output_dir = getwd(), scale = NULL, aoi_year = NULL, view = FALSE, gcs_bucket = NULL, wait = FALSE, zip = FALSE, python_path = NULL, gee_project = NULL, verbose_timer = FALSE) {
  # 1. GEE Auth
  ensure_gee_authenticated(project = gee_project)
  ee <- reticulate::import("ee")

  if (is.null(scale)) scale <- 10
  if (is.null(aoi_year)) aoi_year <- format(Sys.Date(), "%Y")

  # 2. Load Model Metadata
  if (!file.exists(analysis_meta_path)) stop("Metadata file not found: ", analysis_meta_path)
  meta <- jsonlite::fromJSON(analysis_meta_path)

  # 3. Prepare GEE Geometry from df
  bbox <- c(min(df$longitude), min(df$latitude), max(df$longitude), max(df$latitude))
  aoi_geom <- ee$Geometry$Rectangle(bbox)$buffer(1000) # 1km buffer

  # 4. Generate Prediction Map
  img_mosaic <- get_embedding_image(aoi_year, scale)
  
  prediction <- NULL
  if (!meta$is_classifier) {
    # Reducer dot product
    weights_ee <- ee$Image$constant(as.list(meta$weights))$rename(sprintf("A%02d", 0:63))
    prediction <- img_mosaic$multiply(weights_ee)$reduce(ee$Reducer$sum())$add(meta$intercept)$rename("similarity")
  } else {
    # Classifier prediction
    # NOTE: In a pure R implementation, we might need to re-train the GEE classifier
    # if we don't have a serialized version. For now, we'll mark this as limited.
    stop("Classifier extrapolation in pure R currently requires re-training or a serialized GEE model ID.")
  }

  # 5. Output
  m_clean <- gsub("[^a-zA-Z0-9]", "", meta$method)
  tif_path <- file.path(output_dir, paste0(m_clean, "_extrapolation.tif"))
  
  message("Exporting extrapolation map to ", tif_path, "...")
  try(rgee::ee_as_raster(image = prediction, region = aoi_geom, scale = scale, dsn = tif_path), silent = TRUE)

  return(list(map_path = tif_path, method = meta$method))
}

#' Predict at Specific Coordinates
#'
#' @param df Data frame with columns `longitude`, `latitude`, and `year`.
#' @param analysis_meta_paths Vector of paths to metadata JSON files.
#' @param scale Resolution in meters.
#' @param aoi_year Year for Alpha Earth mosaic.
#' @param gee_project GEE Project ID.
#' @param verbose_timer Boolean.
#' @return A list with data (df + similarity) and metrics.
#' @export
predict_at_coords <- function(df, analysis_meta_paths, scale = NULL, aoi_year = NULL, gee_project = NULL, verbose_timer = FALSE) {
  # 1. GEE Auth
  ensure_gee_authenticated(project = gee_project)
  
  if (is.null(scale)) scale <- 10
  
  # 2. Extract Embeddings
  message("Extracting embeddings for prediction coordinates...")
  df_emb <- extract_embeddings(df, scale = scale, gee_project = gee_project)
  
  # 3. Score for each model
  results <- df_emb
  metrics <- list()
  
  for (mp in analysis_meta_paths) {
    if (!file.exists(mp)) next
    meta <- jsonlite::fromJSON(mp)
    m <- meta$method
    
    col_name <- if (length(analysis_meta_paths) > 1) paste0("similarity_", m) else "similarity"
    
    if (!meta$is_classifier) {
      # Reducer (weights): score = (emb * weights) + intercept
      weights <- as.numeric(meta$weights)
      intercept <- as.numeric(meta$intercept)
      
      emb_cols <- sprintf("A%02d", 0:63)
      emb_mat <- as.matrix(df_emb[, emb_cols])
      scores <- (emb_mat %*% weights) + intercept
      
      results[[col_name]] <- as.numeric(scores)
    } else {
      # Classifier scoring needs GEE if we don't have local weights
      message("Warning: Classifier point prediction in R is currently limited.")
      results[[col_name]] <- NA
    }
  }
  
  return(list(data = results, metrics = metrics))
}
