#' Generate Niche Similarity Map
#'
#' This function generates a continuous niche similarity map (dot product) in Google Earth Engine
#' based on the species centroid. The map is returned at the specified resolution.
#'
#' @param df Data frame containing the original survey data (Latitude, Longitude) to determine the AOI.
#' @param analysis_meta_path Path to the JSON metadata file generated by `analyze_embeddings`.
#' @param output_dir Directory where the output map and metadata will be saved. Defaults to current working directory.
#' @param scale Resolution in meters for the output map. Defaults to 10.
#' @param coarse_meta_path Optional. Path to metadata for 1km filtering. If provided, analysis is restricted to 1km pixels > 5th percentile.
#' @param gcs_bucket Optional. GCS bucket name for server-side export. If provided, bypasses local download.
#' @param wait Logical. If TRUE, waits for the GCS export task(s) to complete and shows progress updates.
#' @param zip Logical. If TRUE, zips the output rasters into a single archive (local mode only).
#' @return A list containing the paths to the generated map files, HTML, or GCS export details.
#' @keywords internal
extrapolate <- function(df, analysis_meta_path, output_dir = getwd(), scale = NULL, aoi_year = NULL, view = FALSE, gcs_bucket = NULL, wait = FALSE, zip = FALSE, python_path = NULL, gee_project = NULL, verbose_timer = FALSE) {
  # Resolve python path using the centralized helper
  py_exe <- resolve_python_path(python_path)

  if (is.null(py_exe) || !file.exists(py_exe)) {
    stop("Could not find a valid Python environment.\nPlease ensure Python is installed and detected by `reticulate::py_config()`, or provide the `python_path` argument explicitly.")
  }

  # Create input temp file
  tmp_in <- tempfile(fileext = ".csv")
  write.csv(df, tmp_in, row.names = FALSE)

  # Define output JSON path in the requested directory
  output_json <- file.path(output_dir, paste0("extrapolation_results_", scale, "m.json"))

  message("Calling Python extrapolation logic at scale ", scale, "m...")
  args <- c(
    "-m", "autoSDM.cli", "extrapolate",
    "--input", shQuote(tmp_in),
    "--output", shQuote(output_json),
    "--meta", shQuote(analysis_meta_path),
    "--scale", scale,
    "--year", aoi_year
  )

  if (!is.null(gee_project) && gee_project != "") {
    args <- c(args, "--project", shQuote(gee_project))
  } else {
    # Option B: Try to load from local config if not provided explicitly
    config_file <- file.path(Sys.getenv("HOME"), ".config", "autoSDM", "config.json")
    if (file.exists(config_file)) {
      try(
        {
          conf <- jsonlite::fromJSON(config_file)
          if (!is.null(conf$gee_project) && conf$gee_project != "") {
            args <- c(args, "--project", shQuote(conf$gee_project))
          }
        },
        silent = TRUE
      )
    }
  }


  sa_json_key <- getOption("autoSDM.sa_json_key")
  if (!is.null(sa_json_key) && sa_json_key != "") {
    args <- c(args, "--key", shQuote(sa_json_key))
  }


  if (view) {
    args <- c(args, "--view")
  }

  if (!is.null(gcs_bucket)) {
    args <- c(args, "--gcs-bucket", shQuote(gcs_bucket))
    if (wait) {
      args <- c(args, "--wait")
    }
  } else if (zip) {
    args <- c(args, "--zip")
  }

  status <- .run_command_with_timer(py_exe, args = args, label = "Mapping predictions", active = verbose_timer)

  if (status != 0) {
    unlink(tmp_in)
    stop("Python extrapolation failed.")
  }

  # Read JSON result
  res <- jsonlite::fromJSON(output_json)

  # Stitch tiles if multiple files exist for any layer (only for local download mode)
  if (!view && is.null(gcs_bucket)) {
    message("Checking for tiled outputs to stitch...")
    layer_keys <- names(res)[sapply(res, is.character)] # Get keys with file paths

    for (key in layer_keys) {
      if (length(res[[key]]) > 1) {
        message("Stitching ", key, " (", length(res[[key]]), " tiles)...")
        # Use terra to mosaic
        tryCatch(
          {
            # Load list as SpatRasterCollection
            s_coll <- terra::sprc(res[[key]])
            # Mosaic them
            mfd <- terra::mosaic(s_coll)

            # Define final output name (base name without tiling suffix)
            # res[[key]][1] looks like "path/name_0_0.tif"
            # We want "path/name.tif"
            final_path <- gsub("_0_0\\.tif$", ".tif", res[[key]][1])

            # Write merged file
            terra::writeRaster(mfd, final_path, overwrite = TRUE)

            # Remove tiles
            unlink(res[[key]])

            # Update res object
            res[[key]] <- final_path
          },
          error = function(e) {
            warning("Stitching failed for ", key, ": ", e$message)
          }
        )
      }
    }
  }

  # Clean up input temp file
  unlink(tmp_in)

  if (!is.null(res$monitoring_url)) {
    message("Monitoring URL: ", res$monitoring_url)
    message("You can also monitor via rgee::ee_monitoring().")
  }

  return(res)
}

#' Predict at Specific Coordinates
#'
#' This function takes a data frame of coordinates and returns predictions
#' (similarity or probability) based on a trained model.
#'
#' @param df Data frame with columns `longitude`, `latitude`, and `year`.
#' @param analysis_meta_path Path to the JSON metadata file generated by `analyze_embeddings`.
#' @param scale Resolution in meters for the Alpha Earth embeddings. Defaults to 10.
#' @param python_path Optional. Path to Python executable.
#' @param gee_project Optional. Google Cloud Project ID.
#' @param verbose_timer Optional. Boolean whether to show real-time progress.
#' @return A data frame with original data plus a `similarity` column.
#' @export
predict_at_coords <- function(df, analysis_meta_paths, scale = NULL, aoi_year = NULL, python_path = NULL, gee_project = NULL, verbose_timer = FALSE) {
  py_exe <- resolve_python_path(python_path)

  if (is.null(py_exe) || !file.exists(py_exe)) {
    stop("Could not find a valid Python environment.")
  }

  # Ensure analysis_meta_paths is a vector
  analysis_meta_paths <- as.character(analysis_meta_paths)

  tmp_in <- tempfile(fileext = ".csv")
  tmp_out <- tempfile(fileext = ".csv")
  write.csv(df, tmp_in, row.names = FALSE)

  meta_args <- unlist(lapply(analysis_meta_paths, function(p) c("--meta", shQuote(p))))

  args <- c(
    "-m", "autoSDM.cli", "predict",
    "--input", shQuote(tmp_in),
    "--output", shQuote(tmp_out),
    meta_args,
    "--scale", scale
  )

  if (!is.null(aoi_year)) {
      args <- c(args, "--year", aoi_year)
  }

  if (!is.null(gee_project) && gee_project != "") {
    args <- c(args, "--project", shQuote(gee_project))
  } else {
    # Try to load from local config if not provided explicitly
    config_file <- file.path(Sys.getenv("HOME"), ".config", "autoSDM", "config.json")
    if (file.exists(config_file)) {
      try(
        {
          conf <- jsonlite::fromJSON(config_file)
          if (!is.null(conf$gee_project) && conf$gee_project != "") {
            args <- c(args, "--project", shQuote(conf$gee_project))
          }
        },
        silent = TRUE
      )
    }
  }

  # Use getOption for sa_json_key to avoid lint warnings
  sa_json_key <- getOption("autoSDM.sa_json_key")
  if (!is.null(sa_json_key)) args <- c(args, "--key", shQuote(sa_json_key))

  status <- .run_command_with_timer(py_exe, args = args, label = "Predicting at coordinates", active = verbose_timer)

  if (status != 0) {
    unlink(tmp_in)
    unlink(tmp_out)
    stop("Point prediction failed.")
  }

  res <- read.csv(tmp_out)
  
  metrics <- NULL
  metrics_path <- gsub(".csv$", ".metrics.json", tmp_out)
  if (file.exists(metrics_path)) {
    metrics <- jsonlite::fromJSON(metrics_path)
    unlink(metrics_path)
  }
  
  unlink(tmp_in)
  unlink(tmp_out)

  return(list(data = res, metrics = metrics))
}
